version: '2'
services:
    test_1-app:
        image: test_1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://test_1-mysql:3306/test_1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    test_1-mysql:
        extends:
            file: mysql.yml
            service: test_1-mysql
